export default {
  LOAD_PLAY: 'LOAD_PLAY',
  SET_CURRENT_ACT: 'SET_CURRENT_ACT',
  SET_CURRENT_SCENE: 'SET_CURRENT_SCENE',
  SET_CURRENT_SPEECH: 'SET_CURRENT_SPEECH',
  TRACE_SPEAKER: 'TRACE_SPEAKER',
  SHOW_ACT: 'SHOW_ACT',
  HIDE_ACT: 'HIDE_ACT'
};
